# Generated by Django 5.2.7 on 2025-11-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='data_mappings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
